### ISSUE TITLE
Plans

### ISSUE THREAD

**Issue by AlexeyAndrianov** [AlexAndiranov/money_manager#13]
- [x] Add model "Plans"
- [x] fix model "Balance" (add planned cash and free cash)
- [x] Add model "Recommendation"
- [x] Add controller for "Plans" 
- [x] Add tools to track Plan progress over time
- [x] fix balance controller 
- [x] Add recommendation controller
- [x] Add views
- [x] Add tests 
- [x] Add seeds

**Comment by MikeAndrianov** [comment]
![img_5872](https://cloud.githubusercontent.com/assets/899220/23342233/b9645284-fc67-11e6-9d65-d9f965f8b8ac.JPG)
![img_5873](https://cloud.githubusercontent.com/assets/899220/23342234/b98a7414-fc67-11e6-88af-12a2105649f6.JPG)
