### ISSUE TITLE
Charges for Balance correction

### ISSUE THREAD

**Issue by AlexeyAndrianov** [AlexAndiranov/money_manager#9]
- [x] create Charge model with fields operation_date:date, amount:float, description:text
- [x] add migration, seeds ...
- [x] add controller with actions: create, edit, index, destroy, update
- [x] add views: edit, index, _form
- [x] Charge should belong to User, as well as Balance. Balance should has many charges, as well as User
- [x] When charge is created/updated than balance's amount should be recalculated automatically! (look at callbacks)
- [x] Add tests

**Comment by MikeAndrianov** [comment]
Green – if amount more than 0, otherwise Red (on the index page)
